name: Validate Branch Name

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name follows convention
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name is: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|testing)\/[a-zA-Z0-9._-]+$ ]]; then
            echo "::error ::Invalid branch name. Use one of: feature/*, bugfix/*, testing/*"
            exit 1
          fi
